"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Clop Helper.py']
DATA_FILES = []
OPTIONS = {
    'iconfile':'/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/PicturesFolderIcon.icns',
    'plist': {
        'CFBundleShortVersionString':'1.0.0',
        'LSUIElement': True
        },
    'packages': ['rumps'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
